### ISSUE TITLE
fine-tuned为model/fine-tune-15/model.ckpt-12000；

### ISSUE THREAD

**Issue by Dioxideme** [Aragron-moon/FASPell-EasyUsing#1]
你好，在Faspell-EasyUsing.md 训练csd step2中，fine-tuned为model/fine-tune-15/model.ckpt-12000；
我猜测fine-tune-15可能是fine-tuned，此外model.ckpt-12000可能是step为12000的模型参数。
然而我运行run_pretraining.py后，fine-tuned文件夹下只有这些文件：
![image](https://user-images.githubusercontent.com/33619472/88308035-2a07a800-cd3f-11ea-8c18-1e0d8a7cea48.png)
请问我该选择哪个文件作为fine-tuned的参数，谢谢您！

**Comment by Dioxideme** [comment]
这个问题解决了，tensorflow高版本中保存的模型及其参数格式不同。
此外，您在md文件中提到

> 模型在微调时，指定训练Step为10000步时停止
但是我在run_pretraining.py中看到flags.DEFINE_integer("num_train_steps", 100000, "Number of training steps.")，请问是否需要修改该数值为10000？感谢！

**Comment by Dioxideme** [comment]
这个问题解决了，tensorflow高版本中保存的模型及其参数格式不同。
此外，您在md文件中提到

> 模型在微调时，指定训练Step为10000步时停止

但是我在run_pretraining.py中看到flags.DEFINE_integer("num_train_steps", 100000, "Number of training steps.")，请问是否需要修改该数值为10000？感谢！

**Comment by Aragron-moon** [comment]
> 这个问题解决了，tensorflow高版本中保存的模型及其参数格式不同。
> 此外，您在md文件中提到
> 
> > 模型在微调时，指定训练Step为10000步时停止
> 
> 但是我在run_pretraining.py中看到flags.DEFINE_integer("num_train_steps", 100000, "Number of training steps.")，请问是否需要修改该数值为10000？感谢！

你在run_pretraining.py中设置的num_train_steps就是最后微调模型的步数，这个数值多少是根据需要进行设置的，建议和论文中保持一致，只是我在做实验的时候是设置的120000，你也可以不更改，根据你自己的实验情况决定。很抱歉这么晚才回复你！

**Comment by Dioxideme** [comment]
> > 这个问题解决了，tensorflow高版本中保存的模型及其参数格式不同。
> > 此外，您在md文件中提到
> > > 模型在微调时，指定训练Step为10000步时停止
> > 
> > 
> > 但是我在run_pretraining.py中看到flags.DEFINE_integer("num_train_steps", 100000, "Number of training steps.")，请问是否需要修改该数值为10000？感谢！
> 
> 你在run_pretraining.py中设置的num_train_steps就是最后微调模型的步数，这个数值多少是根据需要进行设置的，建议和论文中保持一致，只是我在做实验的时候是设置的120000，你也可以不更改，根据你自己的实验情况决定。很抱歉这么晚才回复你！

谢谢回复！
